<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head profile="http://gmpg.org/xfn/11">

<title>
<?php if (is_home()) { ?>
<?php bloginfo('name'); ?>
-
<?php bloginfo('description'); ?>
<?php } else { ?>
<?php wp_title($sep = ''); ?>
-
<?php bloginfo('name'); ?>
<?php } ?>
</title>

<meta http-equiv="content-type" content="<?php bloginfo('html_type') ?>; charset=<?php bloginfo('charset') ?>" />
<meta name="description" content="<?php bloginfo('description') ?>" />
<?php if(is_search()) { ?>
<meta name="robots" content="noindex, nofollow" />
<?php }?>
<link rel="alternate" type="application/rss+xml" title="<?php bloginfo('name'); ?> RSS Feed" href="<?php bloginfo('rss2_url'); ?>" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php wp_head(); ?>
<link rel="stylesheet" type="text/css" href="<?php bloginfo('stylesheet_url'); ?>" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php bloginfo('template_directory'); ?>/coin-slider-styles.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php bloginfo('template_directory'); ?>/menusm.css" media="screen" />
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/cufon-yui.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/cufon-libsans.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/cufon-run.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/custom.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/Script_font.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/menusm.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/coin-slider.min.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/jquery.cycle.all.min.js"></script>
<!-- Start Of Script Generated By WP-PageNavi 2.40 -->
<link rel="stylesheet" href="<?php bloginfo('template_directory'); ?>/pagenavi-css.css" type="text/css" media="screen" />
<!-- End Of Script Generated By WP-PageNavi 2.40 -->

</head>
<body>
<?php if (is_front_page()) { ?>
<div id="page_index">
<?php } else { ?>
<div id="page">
<?php } ?>

<!--header-->
<div id="header">

  
<div class="clr"></div>
  <!-- nav1--> 
  <!-- logo-->
  <div class="logo">
    <h1><img src="http://nhwelding.com/wp-content/uploads/2011/08/Logo.png" alt=micro welding"/>
      </h1>
  </div>
  <!-- /logo-->
  <div class="blog_title"> 
    <!--topnav menu-->
   <?php wp_nav_menu( array( 'container_class' => 'topnav', 'theme_location' => 'menu1','menu_class'=>'menusm','fallback_cb'=> 'fallbackmenu' ) ); ?>	

      <div class="clr"></div>
    
    <!--/topnav menu-->
    
    <div class="clr"></div>
  </div>
  <div class="clr"></div>
  <?php if (is_front_page()) { ?>
  <!--slider -->
  <div id="slider"> 
    <!-- start slideshow -->
    <div id="slideshow">
	<?php 
	$featcat = get_option('omg_fcat'); 
	$my_query = new WP_Query('category_name='.$fcat.'&showposts=5');
	while ($my_query->have_posts()) : $my_query->the_post();$do_not_duplicate = $post->ID;
?>  


<div class="slider-item"> 
<?php if ( has_post_thumbnail() ) { ?>
<a href="<?php the_permalink(); ?>" rel="bookmark" title="Permanent Link to <?php the_title_attribute(); ?>">
        		<?php the_post_thumbnail('slider'); ?>
          </a><?php } ?>
	 </div>	 
	 <?php endwhile; ?>
	 </div>
    <!-- end #slideshow -->
    <div class="controls-center">
      <div id="slider_controls"><ul id="slider_nav">
	  <?php 
	$featcat = get_option('omg_fcat'); 
	$my_query = new WP_Query('category_name='.$fcat.'&showposts=5');
	while ($my_query->have_posts()) : $my_query->the_post();$do_not_duplicate = $post->ID;
?>  
        
          <li><?php if ( has_post_thumbnail() ) { ?>
<a href="<?php the_permalink(); ?>" rel="bookmark" title="Permanent Link to <?php the_title_attribute(); ?>">
        		<?php the_post_thumbnail('feat'); ?>
          </a><?php } ?></li>	 
<?php endwhile; ?>

          <!-- Slide 5 -->
        </ul>
      </div>
    </div>
    <div class="clr"></div>
  </div>
  <!--/slider -->
  <?php } else { ?>
  <div class="clr"></div>
  <?php if (is_single()) : ?>
  <h3>Blog</h3>
  <?php else : ?>
  <h3>
    <?php wp_title(''); ?>
  </h3>
  <?php endif; ?>

  <div class="search">
    <?php include (TEMPLATEPATH . '/searchform.php'); ?>
  </div>
  <!--/searchform -->
  <div class="clr"></div>
  <?php } ?>
</div>
<!--/header-->